version: '3'
# In the test override nothing is public
# all of the services run internally where the tests
# are executed
services:
  gt-rabbitmq:
    container_name: gt-rabbitmq-test

  gt-vault-db:
    container_name: gt-vault-db-test
    environment:
      - SQL_DB=testdb

  gt-vault-api:
    container_name: gt-vault-api-test
    environment:
      - DEPLOYMENT_ENVIRONMENT=CI
      - SQL_DB=testdb
      - APPRAISAL_QUEUE='test_appraisal_requests'
      - APPRAISAL_ROUTING_KEY='test_appraisal_requests'
    command: bash -c "
        pytest ./tests/gringotts ${PYTEST_ARGUMENTS}
      "

