version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - rabbitmq_gt_data:/var/lib/rabbitmq/
      - rabbitmq_gt_log:/var/log/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
    profiles: ["develop","standalone"]

  db:
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    env_file:
      - .env
    build:
      context: ./db
      dockerfile: Dockerfile
    volumes:
      - postgres_gt_data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    profiles: ["develop","standalone"]

    healthcheck:
      test:
        [
            "CMD-SHELL", "pg_isready -d $POSTGRES_DB -U $POSTGRES_USER"
        ]
      interval: 5s
      timeout: 5s
      retries: 5

  worker:
    build: ./worker
    profiles: ["standalone"]

    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
      - RABBITMQ=db

    env_file:
      - .env
    command: bash -c "
      uvicorn gringotts.main:app
      --host 0.0.0.0 --port 8080
      --lifespan=on --use-colors --loop uvloop --http httptools
      --reload --log-level debug
      "
    volumes:
      - .:/app
    ports:
      - 8283:8080
      -
  app:
    build: .
    profiles: ["standalone"]

    depends_on:
      - db
    environment:
      - POSTGRES_HOST=db
    env_file:
      - .env
    command: bash -c "
      uvicorn gringotts.main:app
      --host 0.0.0.0 --port 8080
      --lifespan=on --use-colors --loop uvloop --http httptools
      --reload --log-level debug
      "
    volumes:
      - .:/app
    ports:
      - 8283:8080
 
networks:
  default:
    name: gringotts-network

volumes:
  postgres_gt_data:
  rabbitmq_gt_data:
  rabbitmq_gt_log:
